import { setupWorker } from 'msw/browser'
import { handlers } from './handlers.js'

/**
 * Browser-side MSW instance. Intercepts requests made by the running app via
 * the service worker at public/mockServiceWorker.js (generated by
 * `npx msw init public`).
 */
export const worker = setupWorker(...handlers)
